//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoHyB
{

    public partial class frmLogin
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtUsuario;
        protected global::System.Web.UI.WebControls.TextBox txtClave;
        protected global::System.Web.UI.WebControls.Button btnIngresar;
    }
}
