//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
//     Los cambios en este archivo pueden causar un comportamiento incorrecto y se perderan si
//     el codigo se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoHyB
{
    public partial class frmRol
    {
        /// <summary>form1 control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>ScriptManager1 control.</summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>UpdatePanel1 control.</summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        /// <summary>txtCod control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCod;

        /// <summary>Label2 control.</summary>
        protected global::System.Web.UI.WebControls.Label Label2;

        /// <summary>txtNombre control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>Label3 control.</summary>
        protected global::System.Web.UI.WebControls.Label Label3;

        /// <summary>chkEstado control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEstado;

        /// <summary>Label1 control.</summary>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>btnRegistrar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnRegistrar;

        /// <summary>btnActualizar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnActualizar;

        /// <summary>btnEliminar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnEliminar;

        /// <summary>btnHabilitar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnHabilitar;

        /// <summary>UpdatePanel2 control.</summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;

        /// <summary>gvRol control.</summary>
        protected global::System.Web.UI.WebControls.GridView gvRol;
    }
}
